scrapy crawl sport_scraper -o sport.csv
scrapy crawl gb_scraper -o gb.csv
scrapy crawl politics_scraper -o politics.csv
scrapy crawl cities_scraper -o cities.csv
scrapy crawl culture_scraper -o culture.csv
scrapy crawl science_scraper -o science.csv
scrapy crawl society_scraper -o society.csv
scrapy crawl environment_scraper -o environment.csv
scrapy crawl technology_scraper -o technology.csv
scrapy crawl law_scraper -o law.csv